[tool.poetry]
name = "classes_practice"
version = "0.1"
description = "Homework 'Classes'."
repository = "https://github.com/Freddsle/BI_2021_Python/"
authors = ["Yuliya Burankova"]

[tool.poetry.dependencies]
python = ">=3.8"
biopython = "1.79"